FROM node:14

# Create app directory
WORKDIR /usr/src/app

# A wildcard is used to ensure both package.json AND package-lock.json are copied
#COPY package*.json ./
#COPY tsconfig*.json ./

COPY . .

# Install app dependencies
#RUN npm install -g @nestjs/cli
RUN npm install


# Creates a "dist" folder with the production build
RUN npm run build:all

EXPOSE 3000
EXPOSE 4000
EXPOSE 5000
EXPOSE 6000
EXPOSE 8080

CMD ["npm", "run", "start:all"]