version: '3.7'

services:
  api:
    container_name: terangafun-api
    build:
      context: .
      dockerfile: Dockerfile-test
    command: npm run start:all
    ports:
      - 3000:3000
      - 4000:4000
      - 5000:5000
      - 6000:6000
      - 8080:8080
    networks:
      - terangafun-network
networks:
  terangafun-network:
    name : terangafun-network